### ISSUE TITLE
Empty loaded animation.

### ISSUE THREAD

**Issue by Don-Yin** [andfanilo/streamlit-lottie#2]
Hi there, 

Is there a way to empty loaded animation? Something like:

```animation = st_lottie(loadLottieUrl([URL]))```
...some operations
```animation.empty()```

Regards,
Don

**Comment by hodanli** [comment]
how did you solve this isue

**Comment by Don-Yin** [comment]
> how did you solve this isue

Hi,

I didn't. I gave up on streamlit and turned to Dash.

**Comment by hodanli** [comment]
:)

code below did the job for me.

``` python
def pipela(text):
    lottie_container = st.empty()
    with lottie_container:
        st_lottie(lottie_tr, height = 150)
    eng_sentence = pipe(text)[0]['translation_text'] #this is the function body
    lottie_container.empty()
    return eng_sentence
```

**Comment by Don-Yin** [comment]
> :)
> 
> code below did the job for me.
> 
> ```python
> def pipela(text):
>     lottie_container = st.empty()
>     with lottie_container:
>         st_lottie(lottie_tr, height = 150)
>     eng_sentence = pipe(text)[0]['translation_text'] #this is the function body
>     lottie_container.empty()
>     return eng_sentence
> ```

Oh wow. Thanks for sharing! I appreciate it! :D
