### ISSUE TITLE
how to use lottie components as spinner

### ISSUE THREAD

**Issue by fcakyon** [andfanilo/streamlit-lottie#3]
@andfanilo assume i want to show lottie animation as a spinner. how can i delete the lottie component after the task is finished?

sample code:
```python
import time
import streamlit as st
from streamlit_lottie import st_lottie
import requests
def load_lottieurl(url: str):
    r = requests.get(url)
    if r.status_code != 200:
        return None
    return r.json()

lottie_url = "https://assets9.lottiefiles.com/packages/lf20_wvwimamz.json"
lottie_json = load_lottieurl(lottie_url)

with st.spinner(
        text="Downloading.. "
    ):
        st_lottie(lottie_json, height=150, key="loading_gif")
        time.sleep(5)
```

Then the animation does not stop when spinner is finished.

**Comment by andfanilo** [comment]
Hello @fcakyon 

You can wrap your lottie component inside an [empty container](https://docs.streamlit.io/library/api-reference/layout/st.empty) that you clear at the end of the timer.

```python
with st.spinner(text="Downloading.. "):
    lottie_container = st.empty()
    with lottie_container:
        st_lottie(lottie_json, height=150, key="loading_gif")
    time.sleep(5)
    lottie_container.empty() # clear container
```

Hope that does the trick!
Fanilo

___

EDIT: I'm adding this to the library :) will let you know when I get it out!

**Comment by andfanilo** [comment]
@fcakyon 

I've added a new `st_lottie_spinner`:

```python
import time
import streamlit as st
from streamlit_lottie import st_lottie_spinner
import requests


def load_lottieurl(url: str):
    r = requests.get(url)
    if r.status_code != 200:
        return None
    return r.json()


lottie_url = "https://assets9.lottiefiles.com/packages/lf20_wvwimamz.json"
lottie_json = load_lottieurl(lottie_url)

with st.spinner(text="Downloading.. "), st_lottie_spinner(lottie_json, height=150, key="loading_gif"):
    time.sleep(5)
```

Could you upgrade to streamlit-lottie 0.0.3 and tell me if it works on your side?

**Comment by kareemrasheed89** [comment]
> @fcakyon
> 
> I've added a new `st_lottie_spinner`:
> 
> ```python
> import time
> import streamlit as st
> from streamlit_lottie import st_lottie_spinner
> import requests
> 
> 
> def load_lottieurl(url: str):
>     r = requests.get(url)
>     if r.status_code != 200:
>         return None
>     return r.json()
> 
> 
> lottie_url = "https://assets9.lottiefiles.com/packages/lf20_wvwimamz.json"
> lottie_json = load_lottieurl(lottie_url)
> 
> with st.spinner(text="Downloading.. "), st_lottie_spinner(lottie_json, height=150, key="loading_gif"):
>     time.sleep(5)
> ```
> 
> Could you upgrade to streamlit-lottie 0.0.3 and tell me if it works on your side?

Welldone Fanilo.... great work
